2021-09-17 18:38:15,982 INFO    MainThread:118293 [wandb_setup.py:_flush():69] setting env: {}
2021-09-17 18:38:15,982 INFO    MainThread:118293 [wandb_setup.py:_flush():69] setting login settings: {}
2021-09-17 18:38:15,982 INFO    MainThread:118293 [wandb_init.py:_log_setup():342] Logging user logs to /home/indika/Programming/Projects/Python/Artifical-Intelligence/PyTorch/CNN/Intel-Image-Classification-TL/wandb/run-20210917_183815-22xpfvmx/logs/debug.log
2021-09-17 18:38:15,982 INFO    MainThread:118293 [wandb_init.py:_log_setup():343] Logging internal logs to /home/indika/Programming/Projects/Python/Artifical-Intelligence/PyTorch/CNN/Intel-Image-Classification-TL/wandb/run-20210917_183815-22xpfvmx/logs/debug-internal.log
2021-09-17 18:38:15,983 INFO    MainThread:118293 [wandb_init.py:_jupyter_setup():294] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f4999d04150>
2021-09-17 18:38:15,983 INFO    MainThread:118293 [wandb_init.py:init():375] calling init triggers
2021-09-17 18:38:15,983 INFO    MainThread:118293 [wandb_init.py:init():382] wandb.init called with sweep_config: {}
config: {}
2021-09-17 18:38:15,983 INFO    MainThread:118293 [wandb_init.py:init():397] re-initializing run, found existing run on stack: 3ln5enka
2021-09-17 18:38:15,984 INFO    MainThread:118293 [wandb_run.py:finish():1271] finishing run ranuga-d/Intel-Image-Classification-TL/3ln5enka
2021-09-17 18:38:15,984 INFO    MainThread:118293 [wandb_run.py:_atexit_cleanup():1571] got exitcode: 0
2021-09-17 18:38:15,985 INFO    MainThread:118293 [wandb_run.py:_restore():1543] restore
2021-09-17 18:38:16,803 INFO    MainThread:118293 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 729
  total_bytes: 729
}

2021-09-17 18:38:17,420 INFO    MainThread:118293 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 729
  total_bytes: 729
}

2021-09-17 18:38:18,301 INFO    MainThread:118293 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 729
  total_bytes: 24339
}

2021-09-17 18:38:18,403 INFO    MainThread:118293 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 729
  total_bytes: 24339
}

2021-09-17 18:38:18,505 INFO    MainThread:118293 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 729
  total_bytes: 24339
}

2021-09-17 18:38:18,607 INFO    MainThread:118293 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 729
  total_bytes: 24339
}

2021-09-17 18:38:18,708 INFO    MainThread:118293 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 729
  total_bytes: 24339
}

2021-09-17 18:38:18,810 INFO    MainThread:118293 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 729
  total_bytes: 24339
}

2021-09-17 18:38:18,912 INFO    MainThread:118293 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 729
  total_bytes: 24339
}

2021-09-17 18:38:19,014 INFO    MainThread:118293 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 24339
  total_bytes: 24339
}

2021-09-17 18:38:19,116 INFO    MainThread:118293 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 24339
  total_bytes: 24339
}

2021-09-17 18:38:19,218 INFO    MainThread:118293 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 24339
  total_bytes: 24339
}

2021-09-17 18:38:19,320 INFO    MainThread:118293 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 24339
  total_bytes: 24339
}

2021-09-17 18:38:19,421 INFO    MainThread:118293 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 24339
  total_bytes: 24339
}

2021-09-17 18:38:19,523 INFO    MainThread:118293 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 24339
  total_bytes: 24339
}

2021-09-17 18:38:19,625 INFO    MainThread:118293 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 24339
  total_bytes: 24339
}

2021-09-17 18:38:19,726 INFO    MainThread:118293 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 24339
  total_bytes: 24339
}

2021-09-17 18:38:20,109 INFO    MainThread:118293 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 24339
  total_bytes: 24339
}

2021-09-17 18:38:20,211 INFO    MainThread:118293 [wandb_run.py:_wait_for_finish():1693] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 24339
  total_bytes: 24339
}

2021-09-17 18:38:21,305 INFO    MainThread:118293 [wandb_run.py:_show_files():1915] logging synced files
2021-09-17 18:38:21,309 INFO    MainThread:118293 [wandb_init.py:init():424] starting backend
2021-09-17 18:38:21,309 INFO    MainThread:118293 [backend.py:_multiprocessing_setup():72] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-09-17 18:38:21,313 INFO    MainThread:118293 [backend.py:ensure_launched():135] starting backend process...
2021-09-17 18:38:21,346 INFO    MainThread:118293 [backend.py:ensure_launched():140] started backend process with pid: 130156
2021-09-17 18:38:21,347 INFO    MainThread:118293 [wandb_init.py:init():429] backend started and connected
2021-09-17 18:38:21,357 INFO    MainThread:118293 [wandb_run.py:_label_probe_notebook():815] probe notebook
2021-09-17 18:38:21,358 INFO    MainThread:118293 [wandb_init.py:init():477] updated telemetry
2021-09-17 18:38:21,359 INFO    MainThread:118293 [wandb_init.py:init():500] communicating current version
2021-09-17 18:38:22,228 INFO    MainThread:118293 [wandb_init.py:init():505] got version response upgrade_message: "wandb version 0.12.2 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-09-17 18:38:22,229 INFO    MainThread:118293 [wandb_init.py:init():513] communicating run to backend with 30 second timeout
2021-09-17 18:38:22,767 INFO    MainThread:118293 [wandb_init.py:init():540] starting run threads in backend
2021-09-17 18:38:27,773 INFO    MainThread:118293 [wandb_run.py:_console_start():1601] atexit reg
2021-09-17 18:38:27,774 INFO    MainThread:118293 [wandb_run.py:_redirect():1475] redirect: SettingsConsole.WRAP
2021-09-17 18:38:27,774 INFO    MainThread:118293 [wandb_run.py:_redirect():1512] Wrapping output streams.
2021-09-17 18:38:27,775 INFO    MainThread:118293 [wandb_run.py:_redirect():1536] Redirects installed.
2021-09-17 18:38:27,775 INFO    MainThread:118293 [wandb_init.py:init():565] run started, returning control to user process
2021-09-17 18:38:29,879 INFO    MainThread:118293 [wandb_init.py:_pause_backend():256] pausing backend
2021-09-17 18:38:29,880 INFO    MainThread:118293 [jupyter.py:save_ipynb():301] looking for notebook: 00.ipynb
2021-09-17 18:38:50,026 INFO    MainThread:118293 [wandb_run.py:_atexit_cleanup():1571] got exitcode: 0
2021-09-17 18:38:50,027 INFO    MainThread:118293 [wandb_run.py:_restore():1543] restore
2021-09-17 18:38:50,823 INFO    MainThread:118293 [wandb_run.py:_restore():1543] restore
